#! /bin/sh


source ~/.profile

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d          

bspc config border_width        1
bspc config normal_border_color "#000000"
bspc config focused_border_color "#75A4BF"
bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

# this is for floating
bspc rule -a * floating=on

bspc rule -a TelegramDesktop state=floating
bspc rule -a Galculator state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a vlc state=floating

# this is for xtreem download manager floating
bspc rule -a xdman-Main state=floating
#bspc rule -a jetbrains-studio state=fullscreen

#mof net 2021
nitrogen --restore &
polybar top &
picom --experimental-backends &
#bspc config border_width 0







